//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace DOAN0107.Module.BusinessObjects.ORMDataModel1
{

    public partial class Delivery_Bill_Detail : XPObject
    {
        Delivery_Bill fDeliveryBillID;
        [Association(@"Delivery_Bill_DetailReferencesDelivery_Bill")]
        public Delivery_Bill DeliveryBillID
        {
            get { return fDeliveryBillID; }
            set { SetPropertyValue<Delivery_Bill>(nameof(DeliveryBillID), ref fDeliveryBillID, value); }
        }
        short fQuantity;
        public short Quantity
        {
            get { return fQuantity; }
            set { SetPropertyValue<short>(nameof(Quantity), ref fQuantity, value); }
        }
        double fPrice;
        public double Price
        {
            get { return fPrice; }
            set { SetPropertyValue<double>(nameof(Price), ref fPrice, value); }
        }
        Product_Detail fProductDetailID;
        [Association(@"Delivery_Bill_DetailReferencesProduct_Detail")]
        public Product_Detail ProductDetailID
        {
            get { return fProductDetailID; }
            set { SetPropertyValue<Product_Detail>(nameof(ProductDetailID), ref fProductDetailID, value); }
        }
    }

}
