//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace DOAN0107.Module.BusinessObjects.ORMDataModel1
{

    public partial class Delivery_Bill : XPObject
    {
        string fEntryCode;
        public string EntryCode
        {
            get { return fEntryCode; }
            set { SetPropertyValue<string>(nameof(EntryCode), ref fEntryCode, value); }
        }
        Employee fEmployeeID;
        [Association(@"Delivery_BillReferencesEmployee")]
        public Employee EmployeeID
        {
            get { return fEmployeeID; }
            set { SetPropertyValue<Employee>(nameof(EmployeeID), ref fEmployeeID, value); }
        }
        string fReason;
        public string Reason
        {
            get { return fReason; }
            set { SetPropertyValue<string>(nameof(Reason), ref fReason, value); }
        }
        DateTime fCreateTime;
        public DateTime CreateTime
        {
            get { return fCreateTime; }
            set { SetPropertyValue<DateTime>(nameof(CreateTime), ref fCreateTime, value); }
        }
        double fTotalPrice;
        public double TotalPrice
        {
            get { return fTotalPrice; }
            set { SetPropertyValue<double>(nameof(TotalPrice), ref fTotalPrice, value); }
        }
        short fTotalQuantity;
        public short TotalQuantity
        {
            get { return fTotalQuantity; }
            set { SetPropertyValue<short>(nameof(TotalQuantity), ref fTotalQuantity, value); }
        }
        [Association(@"Delivery_Bill_DetailReferencesDelivery_Bill")]
        public XPCollection<Delivery_Bill_Detail> Delivery_Bill_Details { get { return GetCollection<Delivery_Bill_Detail>(nameof(Delivery_Bill_Details)); } }
    }

}
