//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace DOAN0107.Module.BusinessObjects.ORMDataModel1
{

    public partial class Bill : XPObject
    {
        string fEntryCode;
        public string EntryCode
        {
            get { return fEntryCode; }
            set { SetPropertyValue<string>(nameof(EntryCode), ref fEntryCode, value); }
        }
        Customer fCustomerID;
        [Association(@"OrderReferencesUser")]
        public Customer CustomerID
        {
            get { return fCustomerID; }
            set { SetPropertyValue<Customer>(nameof(CustomerID), ref fCustomerID, value); }
        }
        Employee fEmployeeID;
        [Association(@"OrderReferencesEmployee")]
        public Employee EmployeeID
        {
            get { return fEmployeeID; }
            set { SetPropertyValue<Employee>(nameof(EmployeeID), ref fEmployeeID, value); }
        }
        double fTotalPrice;
        public double TotalPrice
        {
            get { return fTotalPrice; }
            set { SetPropertyValue<double>(nameof(TotalPrice), ref fTotalPrice, value); }
        }
        DateTime fCreateTime;
        public DateTime CreateTime
        {
            get { return fCreateTime; }
            set { SetPropertyValue<DateTime>(nameof(CreateTime), ref fCreateTime, value); }
        }
        DateTime fUpdateTime;
        public DateTime UpdateTime
        {
            get { return fUpdateTime; }
            set { SetPropertyValue<DateTime>(nameof(UpdateTime), ref fUpdateTime, value); }
        }
        [Association(@"Order_DetailReferencesOrder")]
        public XPCollection<Bill_Detail> Order_Details { get { return GetCollection<Bill_Detail>(nameof(Order_Details)); } }
    }

}
