//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace DOAN0107.Module.BusinessObjects.ORMDataModel1
{

    public partial class Store : XPObject
    {
        Employee fEmployeeID;
        [Association(@"StoreReferencesEmployee")]
        public Employee EmployeeID
        {
            get { return fEmployeeID; }
            set { SetPropertyValue<Employee>(nameof(EmployeeID), ref fEmployeeID, value); }
        }
        Provider fProviderID;
        [Association(@"StoreReferencesProvider")]
        public Provider ProviderID
        {
            get { return fProviderID; }
            set { SetPropertyValue<Provider>(nameof(ProviderID), ref fProviderID, value); }
        }
        DateTime fDate;
        public DateTime Date
        {
            get { return fDate; }
            set { SetPropertyValue<DateTime>(nameof(Date), ref fDate, value); }
        }
        double fTotalPrice;
        public double TotalPrice
        {
            get { return fTotalPrice; }
            set { SetPropertyValue<double>(nameof(TotalPrice), ref fTotalPrice, value); }
        }
        [Association(@"Store_DetailReferencesStore")]
        public XPCollection<Store_Detail> Store_Details { get { return GetCollection<Store_Detail>(nameof(Store_Details)); } }
    }

}
