//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace DOAN0107.Module.BusinessObjects.ORMDataModel1
{

    public partial class Warehouse_Receipt_Detail : XPObject
    {
        Warehouse_Receipt fWarehouseReceiptID;
        [Association(@"Store_DetailReferencesStore")]
        public Warehouse_Receipt WarehouseReceiptID
        {
            get { return fWarehouseReceiptID; }
            set { SetPropertyValue<Warehouse_Receipt>(nameof(WarehouseReceiptID), ref fWarehouseReceiptID, value); }
        }
        Product_Detail fProductDetailID;
        [Association(@"Store_DetailReferencesProduct_Detail")]
        public Product_Detail ProductDetailID
        {
            get { return fProductDetailID; }
            set { SetPropertyValue<Product_Detail>(nameof(ProductDetailID), ref fProductDetailID, value); }
        }
        short fQuantity;
        public short Quantity
        {
            get { return fQuantity; }
            set { SetPropertyValue<short>(nameof(Quantity), ref fQuantity, value); }
        }
        double fPrice;
        public double Price
        {
            get { return fPrice; }
            set { SetPropertyValue<double>(nameof(Price), ref fPrice, value); }
        }
    }

}
